// <auto-generated />
namespace SwimApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class swimmerssessions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(swimmerssessions));
        
        string IMigrationMetadata.Id
        {
            get { return "202306140214153_swimmers-sessions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
